# Generated by Django 5.1.6 on 2025-03-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
